baseURL: "https://eric.swiftzer.net/"
defaultContentLanguage: zh-tw
languages:
  zh-tw:
    weight: 1
title: EricLog
theme: PaperMod
permalinks:
  posts: /:year/:month/:filename/
pygmentsUseClasses: true
hasCJKLanguage: true
rssLimit: 10
googleAnalytics: G-D93F946T73
disqusShortname: efilm
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: false
menu:
  main:
    - name: Fonts
      url: fonts/
      weight: 10
    - name: Archives
      url: archives/
      weight: 20
    - name: Tags
      url: tags/
      weight: 30
    - name: About
      url: about/
      weight: 50
taxonomies:
  tag: tags
params:
  env: production
  defaultTheme: auto
  homeInfoParams:
    Title: Eric Li
    Content: Android app developer
  socialIcons:
    - name: telegram
      url: "https://telegram.me/ericksli"
    - name: x
      url: "https://twitter.com/ericksli"
    - name: instagram
      url: "https://www.instagram.com/ericksli"
    - name: 500px
      url: "https://500px.com/ericksli"
    - name: medium
      url: "https://medium.com/@ericksli"
    - name: github
      url: "https://github.com/ericksli"
    - name: linkedin
      url: "https://www.linkedin.com/in/ericksli/"
    - name: googleplaystore
      url: "https://play.google.com/store/apps/dev?id=7993122800343932498"
  assets:
    disableHLJS: true
  comments: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
